// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weosjaywpnaanxsxqave.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indlb3NqYXl3cG5hYW54c3hxYXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzk3NDIsImV4cCI6MjA2NzcxNTc0Mn0.1Hd2nCXVAARSylBQd2cnT34CEr02bb_RYQ90aKUOJ30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});